# Generated by Django 5.2.3 on 2025-06-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('webapp', '0002_report_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organisateur',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.report'),
        ),
        migrations.RenameField(
            model_name='apilog',
            old_name='extra',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='status_code',
        ),
        migrations.AddField(
            model_name='apilog',
            name='action',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
