# Generated by Django 5.2.3 on 2025-06-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_report_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badge_reward',
            field=models.ForeignKey(blank=True, help_text='Badge attribué pour cet événement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.badge'),
        ),
        migrations.AddField(
            model_name='event',
            name='points_for_badge',
            field=models.PositiveIntegerField(blank=True, help_text="Points à atteindre pour obtenir le badge de l'événement", null=True),
        ),
    ]
