# Generated by Django 5.2.3 on 2025-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='statut',
            field=models.CharField(default='citoyen', max_length=50),
        ),
    ]
