# Generated by Django 5.2.3 on 2025-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_commentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='statut',
            field=models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En Cours'), ('nettoye', 'Nettoyé')], default='signale', max_length=20),
        ),
    ]
